### ISSUE TITLE
citing_ids vs references

### ISSUE THREAD

**Issue by slvcsl** [allenai/ForeCite#9]
Hi, I'm trying to create a (patent) dataset mirroring the script in [generate_dataset.py](https://github.com/allenai/ForeCite/blob/4c41203d8692de40f018819a78c4fc56d2cf2d7b/forecite/topic_identification/generate_dataset.py#L44). 
However, I'm having trouble understanding how citations/references are managed.

In particular in `full_data_collection_worker`, what's the difference between `citing_ids` and `references`? 
My understanding is that giving a paper P, `citing_ids` contains the ids of all papers that cite P, while `references` contains all P's references. Am I correct?  
Thanks :)

**Comment by dakinggg** [comment]
Hi, apologies that I am just now seeing this! Your interpretation is correct! Just to make it crystal clear, if paper 1 cites paper 2, paper 1 would appear in paper 2's `citing_ids`, and paper 2 would appear in paper 1's `references`.
